Remove dockerize dependency
weseek/growi-docker-compose pull request #77
Opened 2024-11-05 09:04 UTC by onokatio

Docker compose has `healthcheck` feature to check services status.
This PR use it for waiting db and es.
Also Remove dockerize.

2024-11-06 06:07 UTC, onokatio commented
@yuki-takei Could you review this ?

2024-11-06 06:09 UTC, yuki-takei commented
@onokatio Thank you for your contribution 😃 
I'll review it. Please wait a moment.

2024-11-06 10:30 UTC, yuki-takei requested changes

2024-11-06 10:30 UTC, yuki-takei commented on docker-compose.yml
It might be better to add `condition` like following:

```
depends_on:
  mongo:
    condition: service_healthy
```

refs: https://docs.docker.com/compose/how-tos/startup-order/

2024-11-08 05:55 UTC, onokatio commented on docker-compose.yml
Thank you. fixed.

2024-11-08 05:56 UTC, onokatio commented
<img width="1432" alt="Screenshot 2024-11-08 14 54 30" src="https://github.com/user-attachments/assets/25c185ff-f4fe-490c-8324-50d34dd61d30">
<img width="1415" alt="Screenshot 2024-11-08 14 54 42" src="https://github.com/user-attachments/assets/b852b44a-c4ff-4594-843d-8e0ea99d6189">
<img width="1424" alt="Screenshot 2024-11-08 14 54 49" src="https://github.com/user-attachments/assets/1817b117-c943-4634-9c85-d781ea6214c7">

2024-11-08 06:43 UTC, merged

2024-11-08 06:43 UTC, yuki-takei commented
Merged. Thank you! @onokatio